language: objective-c

os: osx
osx_image: xcode7.1
sudo: false

env:
  - LATEST_JAVA=true
  - LATEST_JAVA=false


before_install:
  - chmod +x gradlew
  - chmod +x setupJ2OBJC.sh
  - chmod +x installJava.sh
  - ./setupJ2OBJC.sh
  - ./installJava.sh

